name: Deploy Web Previews
on:
  push:
    branches:
      - preview-**
  pull_request:
    branches:
    - preview-**
jobs:
  build-and-maybe-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Get Branch name
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Build a Dev Instance of this Branch
        run: bundle exec jekyll build

      - name: Deploy to the Preview Page
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          mv _site $BRANCH

          git add $BRANCH/.

          git push gh-pages

          : "${BRANCH:=master}"
